import fireworks.client
from bs4 import BeautifulSoup

class LLMService:
    """Service for LLM processing."""
    
    @staticmethod
    def process_voice_data(raw_text, html_text, api_key):
        """Process voice transcription with LLM."""
        fireworks.client.api_key = api_key
        
        prompt = f"""
            OpenAI Whisper text transcription: {raw_text}
            You are a medical assistant tasked with processing a text transcription generated by OpenAI Whisper from an audio file (e.g., a doctor-patient conversation or medical notes). Follow these steps:

            1. Refine the Text: (MUST be written)
            Improve the text grammatically and logically for better readability and coherence.
            Do not add any new words, sentences, or information not present in the original input.
            Ensure the refined text retains the original meaning and context.

            2. Extract Patient Features: (MUST be written)
            Extract ONLY -be strict on that- the key features of the patient from the following HTML (html_text) in a structured key-value JSON format:
            {html_text}

            3. Reasoning: (MUST be written)
            write your reasons here.
            
            please be strict to the above structure and write the title before (MUST be written) before any section.

            If a specific feature is not mentioned in the input, assign the value null
            to that key (except ICD10 code).
            make sure the output message to be written with the sentence that have (MUST be written) message and be free in any format.
            Explain your reasoning step by step before providing the answer.
        """
        
        try:
            response = fireworks.client.Completion.create(
                model="accounts/fireworks/models/deepseek-v3",
                prompt=prompt,
                max_tokens=100000,
                temperature=0.3,
            )
            
            if response.choices and response.choices[0].text.strip():
                return response.choices[0].text.strip()
            else:
                return raw_text
        except Exception as e:
            raise Exception(f"LLM processing failed: {str(e)}")
    
    @staticmethod
    def process_html_data(raw_text, api_key):
        """Process HTML data with LLM."""
        fireworks.client.api_key = api_key
        
        soup = BeautifulSoup(raw_text, "html.parser")
        
        # Remove unnecessary tags
        for tag in soup(["script", "style", "meta", "link", "head"]):
            tag.decompose()
            
        cleaned_html = soup.prettify()
        
        prompt = f"""
            HTML input: {cleaned_html}
            DeepSeek-V3, please analyze the provided HTML -clincal sheets- input and 
            extract all the key features related to the patient in that HTML format. 
            Ensure the extracted information is structured in a clear and concise format,
            such as a JSON object.
            make sure that JSON output is not nested JSON is just key (description of key) to value (text or number or boolean).
            make sure that the key value output to be related to medical domain as you can.
        """
        
        try:
            response = fireworks.client.Completion.create(
                model="accounts/fireworks/models/deepseek-v3",
                prompt=prompt,
                max_tokens=100000,
                temperature=0.3,
            )
            
            if response.choices and response.choices[0].text.strip():
                return response.choices[0].text.strip()
            else:
                return "{}"
        except Exception as e:
            raise Exception(f"HTML processing failed: {str(e)}")
